apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: kubernetes-controller
    app.kubernetes.io/instance: thanos-receive-controller
    app.kubernetes.io/name: thanos-receive-controller
  name: thanos-receive-controller
  namespace: thanos
