apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-receive-benchmark-config
  namespace: thanos
  labels:
    app.kubernetes.io/component: benchmarking
    app.kubernetes.io/instance: thanos-receive-benchmark
    app.kubernetes.io/name: thanos-receive-benchmark
data:
  config.yaml: |-
    url: http://thanos-receive.thanos.svc.cluster.local:19291/api/v1/receive
    tenants:
      - name: default-tenant
        clients: 50
        reqs: 2
        timeseries:
          - name: up
            labels:
              - name: job
                cardinality: 5
              - name: instance
                cardinality: 10
