apiVersion: v1
kind: ServiceAccount
metadata:
  name: thanos-receive
  namespace: thanos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: list-watch-configmaps
  namespace: thanos
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: thanos-receive
  namespace: thanos
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: list-watch-configmaps
subjects:
  - kind: ServiceAccount
    name: thanos-receive
