name: Docker Image CI

on:
  push:
    branches: [main]
#     tags: [alpine-*]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $GITHUB_REPOSITORY:$GITHUB_SHA
